development:
  adapter: postgresql
  encoding: unicode
  database: ubsapi
  pool: 5
  username: ubsapi
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: ubsapi_test
  pool: 5
  username: ubsapi
  password: root

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: d5jcp37gi98tiq
#   pool: 5
#   username: uemth1rmk18m2o
#   password: p97690d64d3edf98d47a00d7795885a493a1695ba2e3b63047af5e15257c03942